openapi: 3.0.0
info:
  title: AI Textbook Chatbot API
  description: API for the RAG chatbot functionality in the AI-Native Textbook
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: http://localhost:8000
    description: Development server

paths:
  /api/v1/chatbot/query:
    post:
      summary: Submit a query to the RAG chatbot
      description: Allows students to ask questions about textbook content with support for both global and selected-text modes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
                - context_mode
              properties:
                query:
                  type: string
                  description: The question or query from the student
                  example: "Explain the principles of bipedal locomotion in humanoid robots"
                context_mode:
                  type: string
                  enum: [global, selected_text]
                  description: Whether to search all content or just selected text
                  example: "global"
                selected_text:
                  type: string
                  description: Text selected by the user (required if context_mode is selected_text)
                  example: "Bipedal locomotion requires precise balance control..."
                student_id:
                  type: string
                  format: uuid
                  description: Optional student identifier for personalization
                  example: "550e8400-e29b-41d4-a716-446655440000"
                session_id:
                  type: string
                  description: Optional session identifier for conversation context
                  example: "sess_abc123xyz"
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                type: object
                required:
                  - response
                  - sources
                properties:
                  response:
                    type: string
                    description: The chatbot's answer to the query
                    example: "Bipedal locomotion in humanoid robots involves..."
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        chapter_id:
                          type: string
                          format: uuid
                          description: ID of the source chapter
                        chapter_title:
                          type: string
                          description: Title of the source chapter
                        content_snippet:
                          type: string
                          description: Relevant excerpt from the source
                        page_reference:
                          type: string
                          description: Page or section reference in the chapter
                    description: References to textbook content used in the response
                    example: [{"chapter_id": "550e8400-e29b-41d4-a716-446655440001", "chapter_title": "Physical AI Fundamentals", "content_snippet": "Bipedal locomotion requires precise balance control...", "page_reference": "Section 2.3"}]
                  confidence:
                    type: number
                    minimum: 0
                    maximum: 1
                    description: Confidence score of the response
                    example: 0.85
                  session_id:
                    type: string
                    description: Session identifier for continued conversation
                    example: "sess_abc123xyz"
                  conversation_turn:
                    type: integer
                    description: Turn number in the conversation
                    example: 3
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                  - message
                properties:
                  error:
                    type: string
                    example: "validation_error"
                  message:
                    type: string
                    example: "Query must be between 5 and 2000 characters"
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                  - message
                properties:
                  error:
                    type: string
                    example: "rate_limit_exceeded"
                  message:
                    type: string
                    example: "Too many requests, please try again later"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                  - message
                properties:
                  error:
                    type: string
                    example: "internal_error"
                  message:
                    type: string
                    example: "An unexpected error occurred"

  /api/v1/chatbot/session:
    post:
      summary: Create a new chat session
      description: Initializes a new conversation session with context management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                student_id:
                  type: string
                  format: uuid
                  description: Optional student identifier
                context_mode:
                  type: string
                  enum: [global, selected_text]
                  description: Initial context mode for the session
                  default: "global"
                context_length:
                  type: integer
                  description: Number of previous turns to maintain in context
                  default: 5
                  minimum: 1
                  maximum: 20
      responses:
        '200':
          description: Session created successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - session_id
                  - created_at
                properties:
                  session_id:
                    type: string
                    description: Unique identifier for the session
                    example: "sess_abc123xyz"
                  created_at:
                    type: string
                    format: date-time
                    description: Timestamp when session was created
                  context_mode:
                    type: string
                    enum: [global, selected_text]
                    description: Current context mode for the session
                    example: "global"

  /api/v1/chatbot/history:
    get:
      summary: Get chat history for a student
      description: Retrieve previous chat interactions for a specific student
      parameters:
        - name: student_id
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: The student's identifier
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
            maximum: 50
          description: Maximum number of interactions to return
        - name: session_id
          in: query
          required: false
          schema:
            type: string
          description: Filter by specific session
      responses:
        '200':
          description: List of previous chat interactions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    query:
                      type: string
                    response:
                      type: string
                    timestamp:
                      type: string
                      format: date-time
                    context_mode:
                      type: string
                      enum: [global, selected_text]
                    session_id:
                      type: string

  /api/v1/chatbot/feedback:
    post:
      summary: Submit feedback for a chat interaction
      description: Allow users to rate and provide feedback on chatbot responses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - interaction_id
                - rating
              properties:
                interaction_id:
                  type: string
                  format: uuid
                  description: The interaction ID to provide feedback for
                student_id:
                  type: string
                  format: uuid
                  description: Optional student identifier
                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                  description: Rating of the response quality
                helpful:
                  type: boolean
                  description: Whether the response was helpful
                feedback_text:
                  type: string
                  description: Additional textual feedback
                accuracy_rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                  description: Rating of the response accuracy
      responses:
        '200':
          description: Feedback submitted successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                properties:
                  success:
                    type: boolean
                    example: true